//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza_Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza
    {
        public int CustomerID { get; set; }
        public string Pizza1 { get; set; }
        public string Toppings { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
